<?php

/**
 * @file
 * Contains github_oauth2_key.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function github_oauth2_key_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the github_oauth2_key module.
    case 'help.page.github_oauth2_key':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('adds the league github oauth library for creating keys') . '</p>';
      return $output;

    default:
  }
}

